---
- name: Installation Script running
  hosts: localhost
  become: true
  pre_tasks:
    - name: Update packages
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - name: Run zsh file
      ansible.builtin.include_tasks:
        file: ./zsh.yml
      tags: zsh
    - name: Run Core-utils file
      ansible.builtin.include_tasks:
        file: ./core-utils.yml
      tags: core
