---
- name: Installation Script running
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Update pacman package cache
      community.general.pacman:
        update_cache: true
      when: ansible_distribution == 'Archlinux'
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
    - name: Update dnf package cache
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_os_family == 'RedHat'
    - name: Check if yay is installed
      ansible.builtin.command: which yay
      register: yay_check
      changed_when: false
      failed_when: false
      when: ansible_distribution == 'Archlinux'
    - name: Update AUR packages
      ansible.builtin.command: yay -Sua --noconfirm
      when:
        - ansible_distribution == 'Archlinux'
        - yay_check.rc == 0
  tasks:
    - name: Run zsh file
      ansible.builtin.include_tasks:
        file: ./zsh.yml
      tags: zsh
    - name: Run Core-utils file
      ansible.builtin.include_tasks:
        file: ./core-utils.yml
      tags: core
    - name: Post Install scripts
      ansible.builtin.include_tasks:
        file: ./post-install.sh
