- hosts: localhost
  become: true
  pre_tasks:
    - name: Update packages
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - include: ./zsh.yml
    - include: ./core-utils.yml

