---
- name: Installation Script running
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Update packages
      community.general.pacman:
        update_cache: true
    - name: Update AUR packages
      ansible.builtin.shell:
        cmd: yay -Sua
  tasks:
    - name: Run zsh file
      ansible.builtin.include_tasks:
        file: ./zsh.yml
      tags: zsh
    - name: Run Core-utils file
      ansible.builtin.include_tasks:
        file: ./core-utils.yml
      tags: core
