#!/usr/bin/env bash


# script for opening directory with tmux session
session=$(find ~ ~/Documents/ -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
  tmux new-session -s "$session_name" -c "$session" -D
fi

tmux attach -t "$session_name"
