- name: Install zsh on Arch Linux
  community.general.pacman:
    name: zsh
    state: present
  when: ansible_fact_distribution == 'Archlinux'
  tags:
    - zsh

- name: Install zsh on Debian and Ubuntu
  ansible.builtin.apt:
    name:
    - zsh
    - curl
    state: present
    update_cache: true
  when: ansible_fact_os_family == 'Debian'
  tags:
    - zsh

- name: Install zsh on Fedora
  ansible.builtin.dnf:
    name: zsh
    state: present
    update_cache: true
  when: ansible_fact_os_family == 'RedHat'
  tags:
    - zsh
- name: Change Shell
  shell: chsh -s `which zsh`
- name: Install oh-my-zsh
  shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
