#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config window_gap           30 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox ='^II'
bspc rule -a Screenkey manage=off

polybar example &

nitrogen --restore &
picom --experimental-backends &

./bspwmrc
