#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config window_gap           30 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox = 2

polybar example &
nitrogen --restore &
picom --experimental-backends &
alacritty &
./bspwmrc &
